/*
 * Created on 2023-08-25 ( Date ISO 2023-08-25 - Time 16:42:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.startsup.merchant.database.repository;

import com.startsup.merchant.entities.Order;
import com.startsup.merchant.entities.OrderItems;
import com.startsup.merchant.entities.OrderItemsId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring data Jpa repository for "Customers" <br>
 * @author Telosys (http://www.telosys.org/) version 3.3.0
 */
@Repository
public interface OrderItemsRepository extends JpaRepository<OrderItems, OrderItemsId>, JpaSpecificationExecutor<OrderItems> {

}