/*
 * Created on 2023-08-28 ( 12:18:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.startsup.merchant.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import jakarta.persistence.*;

/**
 * JPA entity class for "Merchants"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="merchants", catalog="merchantdb" )
public class Merchants implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=60)
    private String     name ;

    @Column(name="zone_id")
    private Integer    zoneId ;

    @Column(name="description", length=16777215)
    private String     description ;

    @Column(name="rating")
    private BigDecimal rating ;

    @Column(name="address_first_line", nullable=false, length=45)
    private String     addressFirstLine ;

    @Column(name="address_second_line", nullable=false, length=45)
    private String     addressSecondLine ;

    @Column(name="city", nullable=false, length=45)
    private String     city ;

    @Column(name="state", length=45)
    private String     state ;

    @Column(name="pincode", length=10)
    private String     pincode ;

    @Column(name="commission_from", length=10)
    private String     commissionFrom ;

    @Column(name="commission_rate")
    private BigDecimal commissionRate ;

    @Column(name="additional_details", length=1073741824)
    private String     additionalDetails ;

    @Column(name="phone", nullable=false, length=20)
    private String     phone ;


    public void setListOfItems(List<Items> listOfItems) {
        this.listOfItems = listOfItems;
    }

    public Zones getZones() {
        return zones;
    }

    public void setZones(Zones zones) {
        this.zones = zones;
    }

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="merchants")
    @JsonIgnore
    private List<Items> listOfItems ;

    @ManyToOne
//    @JsonIgnore
    @JoinColumn(name="zone_id", referencedColumnName="id", insertable=false, updatable=false)
    private Zones  zones ;

    /**
     * Constructor
     */
    public Merchants() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setZoneId( Integer zoneId ) {
        this.zoneId = zoneId ;
    }
    public Integer getZoneId() {
        return this.zoneId;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setRating( BigDecimal rating ) {
        this.rating = rating ;
    }
    public BigDecimal getRating() {
        return this.rating;
    }

    public void setAddressFirstLine( String addressFirstLine ) {
        this.addressFirstLine = addressFirstLine ;
    }
    public String getAddressFirstLine() {
        return this.addressFirstLine;
    }

    public void setAddressSecondLine( String addressSecondLine ) {
        this.addressSecondLine = addressSecondLine ;
    }
    public String getAddressSecondLine() {
        return this.addressSecondLine;
    }

    public void setCity( String city ) {
        this.city = city ;
    }
    public String getCity() {
        return this.city;
    }

    public void setState( String state ) {
        this.state = state ;
    }
    public String getState() {
        return this.state;
    }

    public void setPincode( String pincode ) {
        this.pincode = pincode ;
    }
    public String getPincode() {
        return this.pincode;
    }

    public void setCommissionFrom( String commissionFrom ) {
        this.commissionFrom = commissionFrom ;
    }
    public String getCommissionFrom() {
        return this.commissionFrom;
    }

    public void setCommissionRate( BigDecimal commissionRate ) {
        this.commissionRate = commissionRate ;
    }
    public BigDecimal getCommissionRate() {
        return this.commissionRate;
    }

    public void setAdditionalDetails( String additionalDetails ) {
        this.additionalDetails = additionalDetails ;
    }
    public String getAdditionalDetails() {
        return this.additionalDetails;
    }

    public void setPhone( String phone ) {
        this.phone = phone ;
    }
    public String getPhone() {
        return this.phone;
    }

    //--- GETTERS FOR LINKS
    public List<Items> getListOfItems() {
        return this.listOfItems;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(zoneId);
        // attribute 'description' not usable (type = String Long Text)
        sb.append("|");
        sb.append(rating);
        sb.append("|");
        sb.append(addressFirstLine);
        sb.append("|");
        sb.append(addressSecondLine);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(pincode);
        sb.append("|");
        sb.append(commissionFrom);
        sb.append("|");
        sb.append(commissionRate);
        // attribute 'additionalDetails' not usable (type = String Long Text)
        sb.append("|");
        sb.append(phone);
        return sb.toString(); 
    } 

}
