/*
 * Created on 2023-08-29 ( 12:15:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.startsup.merchant.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

/**
 * JPA entity class for "Order"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="order", catalog="merchantdb" )
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="customer_id", nullable=false)
    private Integer    customerId ;

    @Column(name="merchant_id", nullable=false)
    private Integer    merchantId ;

    @Column(name="subtotal", nullable=false)
    private Double     subtotal ;

    @Column(name="store_charge", nullable=false)
    private Double     storeCharge ;

    @Column(name="delivery_charge", nullable=false)
    private Double     deliveryCharge ;

    @Column(name="order_tax", nullable=false)
    private Double     orderTax ;

    @Column(name="total", nullable=false)
    private Double     total ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_start_time", nullable=false)
    private Date       orderStartTime ;

    public void setUser(User user) {
        this.user = user;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    public void setListOfOrderItems(List<OrderItems> listOfOrderItems) {
        this.listOfOrderItems = listOfOrderItems;
    }

    public void setMerchants(Merchants merchants) {
        this.merchants = merchants;
    }

    @Column(name="order_status", nullable=false, length=50)
    private String     orderStatus ;

    @Column(name="payment_mode", length=45)
    private String     paymentMode ;

    @Column(name="order_type", length=45)
    private String     orderType ;

    @Column(name="delivery_rating")
    private BigDecimal deliveryRating ;

    @Column(name="merchant_rating")
    private BigDecimal merchantRating ;

    @Column(name="delivery_person")
    private Integer    deliveryPerson ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_status_updated_timestamp")
    private Date       lastStatusUpdatedTimestamp ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_completed_timestamp")
    private Date       orderCompletedTimestamp ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="delivery_person", referencedColumnName="id", insertable=false, updatable=false)
    @JsonIgnore
    private User       user ; 

    @ManyToOne
    @JoinColumn(name="customer_id", referencedColumnName="id", insertable=false, updatable=false)
    @JsonIgnore
    private Customers  customers ; 

    @OneToMany(mappedBy="order")
    @JsonIgnore
    private List<OrderItems> listOfOrderItems ; 

    @ManyToOne
    @JoinColumn(name="merchant_id", referencedColumnName="id", insertable=false, updatable=false)
    @JsonIgnore
    private Merchants  merchants ; 


    /**
     * Constructor
     */
    public Order() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setCustomerId( Integer customerId ) {
        this.customerId = customerId ;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setMerchantId( Integer merchantId ) {
        this.merchantId = merchantId ;
    }
    public Integer getMerchantId() {
        return this.merchantId;
    }

    public void setSubtotal( Double subtotal ) {
        this.subtotal = subtotal ;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }

    public void setStoreCharge( Double storeCharge ) {
        this.storeCharge = storeCharge ;
    }
    public Double getStoreCharge() {
        return this.storeCharge;
    }

    public void setDeliveryCharge( Double deliveryCharge ) {
        this.deliveryCharge = deliveryCharge ;
    }
    public Double getDeliveryCharge() {
        return this.deliveryCharge;
    }

    public void setOrderTax( Double orderTax ) {
        this.orderTax = orderTax ;
    }
    public Double getOrderTax() {
        return this.orderTax;
    }

    public void setTotal( Double total ) {
        this.total = total ;
    }
    public Double getTotal() {
        return this.total;
    }

    public void setOrderStartTime( Date orderStartTime ) {
        this.orderStartTime = orderStartTime ;
    }
    public Date getOrderStartTime() {
        return this.orderStartTime;
    }

    public void setOrderStatus( String orderStatus ) {
        this.orderStatus = orderStatus ;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }

    public void setPaymentMode( String paymentMode ) {
        this.paymentMode = paymentMode ;
    }
    public String getPaymentMode() {
        return this.paymentMode;
    }

    public void setOrderType( String orderType ) {
        this.orderType = orderType ;
    }
    public String getOrderType() {
        return this.orderType;
    }

    public void setDeliveryRating( BigDecimal deliveryRating ) {
        this.deliveryRating = deliveryRating ;
    }
    public BigDecimal getDeliveryRating() {
        return this.deliveryRating;
    }

    public void setMerchantRating( BigDecimal merchantRating ) {
        this.merchantRating = merchantRating ;
    }
    public BigDecimal getMerchantRating() {
        return this.merchantRating;
    }

    public void setDeliveryPerson( Integer deliveryPerson ) {
        this.deliveryPerson = deliveryPerson ;
    }
    public Integer getDeliveryPerson() {
        return this.deliveryPerson;
    }

    public void setLastStatusUpdatedTimestamp( Date lastStatusUpdatedTimestamp ) {
        this.lastStatusUpdatedTimestamp = lastStatusUpdatedTimestamp ;
    }
    public Date getLastStatusUpdatedTimestamp() {
        return this.lastStatusUpdatedTimestamp;
    }

    public void setOrderCompletedTimestamp( Date orderCompletedTimestamp ) {
        this.orderCompletedTimestamp = orderCompletedTimestamp ;
    }
    public Date getOrderCompletedTimestamp() {
        return this.orderCompletedTimestamp;
    }

    //--- GETTERS FOR LINKS
    public User getUser() {
        return this.user;
    } 

    public Customers getCustomers() {
        return this.customers;
    } 

    public List<OrderItems> getListOfOrderItems() {
        return this.listOfOrderItems;
    } 

    public Merchants getMerchants() {
        return this.merchants;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(customerId);
        sb.append("|");
        sb.append(merchantId);
        sb.append("|");
        sb.append(subtotal);
        sb.append("|");
        sb.append(storeCharge);
        sb.append("|");
        sb.append(deliveryCharge);
        sb.append("|");
        sb.append(orderTax);
        sb.append("|");
        sb.append(total);
        sb.append("|");
        sb.append(orderStartTime);
        sb.append("|");
        sb.append(orderStatus);
        sb.append("|");
        sb.append(paymentMode);
        sb.append("|");
        sb.append(orderType);
        sb.append("|");
        sb.append(deliveryRating);
        sb.append("|");
        sb.append(merchantRating);
        sb.append("|");
        sb.append(deliveryPerson);
        sb.append("|");
        sb.append(lastStatusUpdatedTimestamp);
        sb.append("|");
        sb.append(orderCompletedTimestamp);
        return sb.toString(); 
    } 

}
