/*
 * Created on 2023-08-29 ( 12:15:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.startsup.merchant.entities;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

/**
 * JPA entity class for "Zones"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="zones", catalog="merchantdb" )
public class Zones implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=10)
    private String     name ;

    @Column(name="description", nullable=false, length=45)
    private String     description ;

    @Column(name="additional_details", length=1073741824)
    private String     additionalDetails ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="zones")
    @JsonIgnore
    private List<Customers> listOfCustomers ;

    public void setListOfCustomers(List<Customers> listOfCustomers) {
        this.listOfCustomers = listOfCustomers;
    }

    public void setListOfMerchants(List<Merchants> listOfMerchants) {
        this.listOfMerchants = listOfMerchants;
    }

    @OneToMany(mappedBy="zones")
    @JsonIgnore
    private List<Merchants> listOfMerchants ; 


    /**
     * Constructor
     */
    public Zones() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setAdditionalDetails( String additionalDetails ) {
        this.additionalDetails = additionalDetails ;
    }
    public String getAdditionalDetails() {
        return this.additionalDetails;
    }

    //--- GETTERS FOR LINKS
    public List<Customers> getListOfCustomers() {
        return this.listOfCustomers;
    } 

    public List<Merchants> getListOfMerchants() {
        return this.listOfMerchants;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(description);
        // attribute 'additionalDetails' not usable (type = String Long Text)
        return sb.toString(); 
    } 

}
